## Papers {.central}

[Articles in Refereed Journals]{.blue}

-   Gerli, S., Cigna, T., Ascari, R., Migliorati, S., and **Borrotti, M.** (2024) Beyond human labelling: an automatic topic identification framework for big web data, *Electronic Journal of Applied Statistical Analysis*, accepted.

-   Zangirolami, V., and **Borrotti, M.** (2024). Dealing with uncertainty: balancing exploration and exploitation in deep recurrent reinforcement learning. *Knowledge-Based Systems*, Vol. 293, p. 1-11, [10.1016/j.knosys.2024.111663](https://dx.doi.org/10.1016/j.knosys.2024.111663).

-   **Borrotti, M.** (2024). Quantifying Uncertainty with Conformal Prediction for Heating and Cooling Load Forecasting in Building Performance Simulation. *Energies*, Vol. 17, p. 1-13, [10.3390/en17174348](https://dx.doi.org/10.3390/en17174348).

-   **Borrotti, M.**, Sambo, F., and Mylona, K. (2023). Multi-objective optimisation of split-plot designs. *Econometrics and Statistics*, Vol. 28, p. 163-172, [10.1016/j.ecosta.2022.04.001](https://dx.doi.org/10.1016/j.ecosta.2022.04.001).

-   **Borrotti, M.**, Rabasco, M., Santoro, A. (2023). Using accounting information to predict aggressive tax location decisions by European groups, *Economic Systems*, Vol. 43, 101090, [10.1016/j.ecosys.2023.101090](https://dx.doi.org/10.1016/j.ecosys.2023.101090).

-   Riboni, A., Ghioldi, N., Candelieri, A., and **Borrotti, M.** (2022) Bayesian optimization and deep learning for steering wheel angle prediction, *Scientific Reports*, Vol. 12, pp. 1–13, [10.1038/s41598-022-12509-6](https://dx.doi.org/10.1038/s41598-022-12509-6).

-   Lucarelli, G., and **Borrotti, M.** (2020) A deep Q-learning portfolio management framework for the cryptocurrency market, *Neural Computing and Applications*, Vol.32, pp. 17229—17244, [10.1007/s00521-020-05359-8](https://dx.doi.org/10.1007/s00521-020-05359-8).

-   **Borrotti, M.**, Sambo, F., Mylona, K., and Gilmour, S. (2017) A multi-objective coordinate-exchange two-phase local search algorithm for multi-stratum experiments, *Statistics and Computing*, Vol. 27, pp. 469–481, [10.1007/s11222-016-9633-6](https://dx.doi.org/10.1007/s11222-016-9633-6).

-   **Borrotti, M.**, Lanzarone, E., Manganini, F., Ortelli, S., Pievatolo, A., and Tonetti, C. (2017) Defect minimization and feature control in electrospinning through design of experiments, *Journal of Applied Polymer*, Vol. 134, [10.1002/app.44740](https://dx.doi.org/10.1002/app.44740).

-   Piccolomini, A. A., Fiabon, A., **Borrotti, M.**, and De Lucrezia, D. (2017) Optimization of thermophilic trans-isoprenyl diphosphate synthase expression in Escherichia coly by response surface methodology, *Biotechnology and Applied Biochemistry*, Vol. 64, pp. 70-78, [10.1002/bab.1459](https://dx.doi.org/10.1002/bab.1459).

-   **Borrotti, M.**, Minervini, G., De Lucrezia, P., and Poli, I. (2016) Naïve Bayes ant colony optimization for designing high dimensional experiments, *Applied Soft Computing*, Vol. 49, pp. 459–468, [10.1016/j.asoc.2016.08.018](https://dx.doi.org/10.1016/j.asoc.2016.08.018).

-   **Borrotti, M.**, Pievatolo, A., Degiorgi, A., Critelli, I., and Colledani, M. (2016) A computer-aided methodology for the optimization of electrostatic separation processes in recycling, *Applied Stochastic Models in Business and Industry*, Vol. 32, pp. 133–148, [10.1002/asmb.2128](https://dx.doi.org/10.1002/asmb.2128).

-   Coccon, F., Bossi, G., **Borrotti, M.**, P. Torricelli, and P. Franzoi (2015) A land-use perspective for wildlife strike risk assessment at airports: the Attraction Risk Index, *PlosOne*, Vol. 10, [10.1371/journal.pone.0128363](https://dx.doi.org/10.1371/journal.pone.0128363).

-   Zennaro, P., Kehrwald, N.M., McConnel, J.R., Schüpbach, S., Maselli, O., Marlon, J., Vallelonga, P., Leuenberger, D., Zangrando, R., Spolaor, M., **Borrotti, M.**, Barbaro, E., Gambaro, A., and Barbante, C. (2014) Fire in ice: two millennia of northern hemisphere fire history from the Greenland NEEM ice core, *Climate of the Past*, Vol. 10, pp. 1905–1925, [10.5194/cpd-10-809-2014](https://dx.doi.org/10.5194/cpd-10-809-2014).

-   **Borrotti, M.**, De March, M., Slanzi, D., Poli, I. (2014) Designing lead optimisation of MMP-12 Inhibitors, *Computational and Mathematical Methods in Medicine*, Vol. 2014, pp. 1–8, [10.1155/2014/258627](https://dx.doi.org/10.1155/2014/258627).

-   Sambo, F., **Borrotti, M.**, and Mylona, K. (2014) Coordinate-exchange two-phase local search: an optimal algorithm for D-efficient and I-efficient second-order split-plot designs, *Computational Statistics and Data Analysis*, Vol. 71, pp. 1193–1207, [10.1016/j.csda.2013.03.015](https://dx.doi.org/10.1016/j.csda.2013.03.015).

-   Ferrari, D., **Borrotti, M.**, and De March, D., Response improvement in complex experiments by co-information composite likelihood optimization, *Statistics and Computing*, Vol. 24, pp. 351–363, [10.1007/s11222-013-9374-8](https://dx.doi.org/10.1007/s11222-013-9374-8).

-   Zemella, G., De March, D., **Borrotti, M.**, and Poli, I. (2011) Optimised design of energy efficient building façades via evolutionary neural networks, *Energy and Buildings*, vol. 43, pp. 3297– 3302, [10.1016/j.enbuild.2011.10.006](https://dx.doi.org/10.1016/j.enbuild.2011.10.006).

-   Pizza, F., Contardi, S., Baldi Antognini, A., Zagoraiou, M., **Borrotti, M.**, Mostacci, B., Mondini, and S., Cirignotta, F. (2010) Sleep quality and car accidents in adolescents, *Journal of Clinical Sleep Medicine*, Vol. 6, No. 1, [10.5664/jcsm.27708](https://dx.doi.org/10.5664/jcsm.27708).

[Books and Chapters in Books]{.blue}

-   Riboni, A., Candelieri, A., and **Borrotti, M.** (2022) Deep autonomous agents comparison for self-driving cars, In: G. Nicosia et al. (Eds.) *Machine Learning, Optimization, and Data Science. LOD 2021. Lecture Notes in Computer Science*, Vol. 13163, pp. 201–213, Springer-Verlag.

-   Lucarelli, G., and **Borrotti, M.** (2019) A deep reinforcement learning approach for automated cryptocurrency trading, In J. MacIntyre et al. (Eds.), *Artificial Intelligence Applications and Innovations*, Vol. 559, pp. 247–258, Springer-Verlag.

-   **Borrotti, M.**, and Pievatolo, A. (2016) A multi-objective Bayesian sequential design based on Pareto optimality, *Advances in Model-Oriented Design and Analysis, Contributions to Statistics*, pp. 47-54, Springer-Verlag, Springer-Verlag.

-   De March, D., **Borrotti, M.**, Sartore, L., Slanzi, D., Podestà, L., and Poli, I. (2015) A predictive approach based on neural network models for building automation systems, In S. Bassis et al. (Eds.), *Advances in Neural Networks: Computational and Theoretical Issues, Smart Innovation Systems and Technology*, Vol. 37, pp. 253-262, Springer-Verlag.

-   Slanzi, D., **Borrotti, M.**, Orlando, D., De March, D.s, Giove, S., and Poli, I. (2014) Qualitative Particle Swarm Optimization (Q-PSO) for energy efficient building designs, In C. Pizzuti et al. (Eds.), *Advances in Artificial Life and Evolutionary Computation, Communications in Computer and Information Science*, Vol. 445, pp. 13–25, Springer-Verlag.

-   Ferrari, D., and **Borrotti, M.** (2013) Maximum entropy design in high dimensions by composite likelihood modeling, In D. Ucínski et al. (Eds.), *Advances in Model-Oriented Design and Analysis, Contributions to Statistics*, pp. 73–80, Springer-Verlag.

-   **Borrotti, M.**, and Poli, I. (2013) Naïve Bayes ant colony optimization for experimental design, In R. Kruse et al. (Eds.), *Synergies of Soft Computing and Statistics for Intelligent Data Analysis, Advances in Intelligent Systems and Computing*, Vol. 190, pp. 489–497, Springer-Verlag.

-   **Borrotti, M.**, De Lucrezia, D., Minervini, G., and Poli, I., A model based ant colony design for the protein engineering problems, In M. Dorigo et al. (Eds.), *ANTS 2010, Lecture Notes in Computer Science*, Vol. 6263, pp. 352–359, Springer-Verlag, 2010.

[Conference Proceedings and Technical Reports]{.blue}

-   Bacino, V., Zoccarato, A., Liberati, C., and **Borrotti, M.** (2021) Statistical learning for credit risk modelling. In *Book of Short Papers SIS 2021*, Vol. 2021, pp. 1624–1629.

-   Bogni, S., Slanzi, D., and **Borrotti, M.** (2021) Q-learning estimation techniques for Dynamic Treatment Regime . In *Book of Short Papers SIS 2021*, Vol. 2021, pp. 578–583.

-   Hassan Elbedawi Omar, M., and **Borrotti, M.** (2018) Customer churn prediction based on eXtreme gradient boosting classifier. In *Book of Short Papers SIS 2018*, Vol. 2018, pp. 775–780.

-   **Borrotti, M.** (2009) A model based algorithm for evolutionary design of experiments, In F. Hutter et al. (Eds.), *SLS-DS 2009, Technical Report N. TR/IRIDIA/2009-024*, IRIDIA.
